# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        name: _session

    #esi: true
    #fragments: true
    php_errors:
        log: true

    form:
        legacy_error_messages: false

    http_client:
        scoped_clients:
            .client:
                base_uri: '%env(string:setting:API_DOMAIN)%'
                headers:
                    Accept: 'application/json'
                    Authorization: '%env(string:setting:PLATFORM_API_KEY)%'

    http_method_override: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        session:
            handler_id: AsyncAws\DynamoDbSession\SessionHandler

    services:
        AsyncAws\DynamoDbSession\SessionHandler:
            class: AsyncAws\DynamoDbSession\SessionHandler
            arguments:
                - '@async_aws.client.dynamo_db'
                -   table_name: '%env(SESSION_TABLE_NAME)%'
