framework:
    enabled_locales:
        - en-GB
        - vn-VN
    default_locale: en-GB
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
