coverage:
    status:
        project:
            default:
                enabled: true
                target: auto # auto % coverage target
                threshold: 5%  # allow for 5% reduction of coverage without failing
        patch: false
        changes: false
