<?php

declare(strict_types=1);

namespace App\Domain\Integration;

enum Topic: string
{
    case SIMPLE_REGISTRATION_CREATED = 'SIMPLE_REGISTRATION_CREATED';
    case TRANSACTION_CONFIRMED = 'TRANSACTION_CONFIRMED';
    case IDV_UPLOADED = 'IDV_UPLOADED';
    case IDV_RESULT_RECEIVED = 'IDV_RESULT_RECEIVED';
    case COMPANY_VERIFIED = 'COMPANY_VERIFIED';
    case COMPANY_REJECTED = 'COMPANY_REJECTED';
    case REFUND_REQUESTED = 'REFUND_REQUESTED';
    case REFUND_EXECUTED = 'REFUND_EXECUTED';
    case ADJUSTMENT_EXECUTED = 'ADJUSTMENT_EXECUTED';
    case REFUND_PAYABLE = 'REFUND_PAYABLE';
    case PAYMENT_METHODS_PREFERENCES_UPDATED = 'PAYMENT_METHODS_PREFERENCES_UPDATED';
    case FX_ORDER_CREATED = 'FX_ORDER_CREATED';
    case FX_RATES_UPDATED = 'FX_RATES_UPDATED';
    case FX_SETTLEMENT_CREATED = 'FX_SETTLEMENT_CREATED';
    case FIRST_APP_LOGIN = 'FIRST_APP_LOGIN';
    case DEFAULT_BANK_ACCOUNT_CHANGED = 'DEFAULT_BANK_ACCOUNT_CHANGED';
    case BETA_FEATURE_INTEREST = 'BETA_FEATURE_INTEREST';
    case PAYOUT_BLOCK_CREATED = 'PAYOUT_BLOCK_CREATED';
    case DISPUTE_CREATED = 'DISPUTE_CREATED';
    case CHARGEBACK_CREATED = 'CHARGEBACK_CREATED';
    case DAILY_REPORT_GENERATED = 'DAILY_REPORT_GENERATED';
}
