<?php

declare(strict_types=1);

namespace App\Domain\Permission;

enum Module: string
{
    case CHARGE = 'CHARGE';
    case DASHBOARD = 'DASHBOARD';
    case TRANSACTIONS = 'TRANSACTIONS';
    case TRANSACTIONS_REFUND_REQUEST = 'TRANSACTIONS_REFUND_REQUEST';
    case TRANSACTIONS_VOID = 'TRANSACTIONS_VOID';
    case ORDERS = 'ORDERS';
    case PAYMENT_REQUESTS = 'PAYMENT_REQUESTS';
    case CHECKOUT = 'CHECKOUT';
    case CHECKOUT_PRODUCTS = 'CHECKOUT_PRODUCTS';
    case CHECKOUT_CATEGORIES = 'CHECKOUT_CATEGORIES';
    case CHECKOUT_STORE_SETTINGS = 'CHECKOUT_STORE_SETTINGS';
    case CHECKOUT_LOCATIONS = 'CHECKOUT_LOCATIONS';
    case BALANCE = 'BALANCE';
    case BALANCE_ACCOUNTS = 'BALANCE_ACCOUNTS';
    case BALANCE_REMITTANCE_HISTORY = 'BALANCE_REMITTANCE_HISTORY';
    case CONNECT = 'CONNECT';
    case EVENTS = 'EVENTS';
    case COMPANY = 'COMPANY';
    case PROFILE = 'PROFILE';
    case SETTINGS = 'SETTINGS';
    case SETTINGS_DETAILS = 'SETTINGS_DETAILS';
    case SETTINGS_DETAILS_BRANDING = 'SETTINGS_DETAILS_BRANDING';
    case SETTINGS_DETAILS_INFO = 'SETTINGS_DETAILS_INFO';
    case SETTINGS_DETAILS_ADDRESS = 'SETTINGS_DETAILS_ADDRESS';
    case SETTINGS_DETAILS_CONTACT = 'SETTINGS_DETAILS_CONTACT';
    case SETTINGS_PAYMENTS = 'SETTINGS_PAYMENTS';
    case SETTINGS_BANK = 'SETTINGS_BANK';
    case SETTINGS_USERS = 'SETTINGS_USERS';
    case SETTINGS_LOCALISATION = 'SETTINGS_LOCALISATION';
    case SETTINGS_BILLING = 'SETTINGS_BILLING';
    case CUSTOM_GET_SYSTEM_EMAILS = 'CUSTOM_GET_SYSTEM_EMAILS';
    case APP_POS = 'APP_POS';
    case APP_POS_KEYPAD = 'APP_POS_KEYPAD';
    case APP_POS_PRODUCTS = 'APP_POS_PRODUCTS';
    case CUSTOMER_DIRECTORY = 'CUSTOMER_DIRECTORY';
    case CUSTOMER_GROUPS = 'CUSTOMER_GROUPS';
    case INVOICES = 'INVOICES';
    case PAYMENT_QR_CODE = 'PAYMENT_QR_CODE';
    case TERMS = 'TERMS';
    case SHIFTS = 'SHIFTS';
    case INTEGRATIONS = 'INTEGRATIONS';
    case BILLS = 'BILLS';
    case BILLS_SCHEDULE = 'BILLS_SCHEDULE';
    case BILLS_SETTINGS = 'BILLS_SETTINGS';
    case SUPPLIERS = 'SUPPLIERS';
}
